"""add ai_style

Revision ID: 8026f3ef0f28
Revises: f9c57dca9401
Create Date: 2026-09-21 13:39:07.453018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8026f3ef0f28'
down_revision: Union[str, Sequence[str], None] = 'f9c57dca9401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_code', sa.VARCHAR(length=10), server_default=sa.text("'ru'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
