"""monitoring source fields nullable

Revision ID: d20875a1ec59
Revises: e26efd88b5c9
Create Date: 2026-10-01 23:12:46.840090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20875a1ec59'
down_revision: Union[str, Sequence[str], None] = 'e26efd88b5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitoringresourses', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('monitoringresourses', 'marketplace_shop_id_only',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitoringresourses', 'marketplace_shop_id_only',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('monitoringresourses', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
